services:
  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/amirrojas/workspace/KOTLIN/currency_back/BDdata:/var/lib/postgresql/data
    networks:
          - default

  currency-converter:
    image: demo:3.0.0
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      URL: ${POSTGRES_URL}
      USER_NAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /home/amirrojas/workspace/KOTLIN/logs_back:/home/amirrojas/workspace/KOTLIN/logs_back
    depends_on:
      - postgres
    networks:
        - default

  angular:
    image: angular-software:3.0.0
    ports:
      - "4200:80"
    volumes:
      - /home/amirrojas/workspace/KOTLIN/currency_front/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
        - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

